### ISSUE TITLE
Brainstorm - Parser AST Format

### ISSUE THREAD

**Issue by jhayley** [jhayley/bondage.js#20]
Separating this discussion of this out of #18 (which is separate but not unrelated)

Conrad's comment [here](https://github.com/jhayley/bondage.js/issues/18#issuecomment-310482365) is a good example of an existing format.

Also discussed things like internationalization, which i feel like would be something more on the parser end of things.

**Comment by ephread** [comment]
This [gist](https://gist.github.com/ephread/204cb0e7376c9688d269bd0f954d45c4) describes a pseudo-yarn file with its corresponding AST (as generated by the implementation of my [local branch](https://github.com/ephread/bondage.js/tree/parser-update)).

So basically, the runner would traverse the tree, from the starting node (direct child of the root node). Important points, from the top of my head:

- when a conditional node is encountered, the _runner_ will resolve it recursively, to retrieve the appropriate sub command/text/link/etc. nodes, based on the condition; I've got an almost-working solver, but it's not pushed yet.
- when a link node is encountered, the _runner_ should probably look at its siblings to find if other link nodes / option nodes are present and bundles them together for the _renderer_.
- Yarn nodes (renamed `DialogNode` in the AST) are all children of the root node; they are currently stored in an array, but it would probably make more sense to store them in a hash (as did the earlier versions of the parser).

The structure is fairly generic and flexible, we can easily add new type of nodes and new properties. (like a sound node, a parallel action node containing other nodes, an actor fade node, etc.)

Let me know what you all think of it.

**Comment by jhayley** [comment]
Cool, this is definitely in line with what i was thinking. though i think there's one thing that needs to be worked out:

>when a link node is encountered, the runner should probably look at its siblings to find if other link nodes / option nodes are present and bundles them together for the renderer.

I think the way this would need to be handled is a bit finicky. Especially thinking about the link node nested in the if statement. If a link is encountered, would we just run to the end of the dialog node and try to find more? Basically mandating that links need to be at the end of each node. I..think that makes sense? And I thought I had an argument about wanting to put link in the middle of a dialog node and having the option of just continuing past it but I'm not sure that makes sense for 99% of the use cases. Maybe I've been playing too much ladykiller in a bind

**Comment by damian0815** [comment]
Hey folks, I was very happy to stumble across this package recently. As my first effort at personal game dev I'm chipping away a dialog-driven RPG based on New Zealand history, trying to approach it with a post-colonial mindset. 

I've only got a few options in place but I can already see the value of the shortcut-option feature that Yarnspinner supports. And, although I don't yet have a use for setting and getting variables, I can see that I'll need it pretty soon. @ephread I tried using your `parser-update` branch but it didn't play nice with `npm install` (`enoent ENOENT: no such file or directory, chmod '<......>/node_modules/bondage/bin/bondage_runner.js`), unless I'm doing something wrong.

Reading through this page I guess it's still a WIP. I'd be keen to contribute to the development if I could. Unfortunately I have very little experience with javascript and no experience at all with script parsing/lexing, so I'm not sure how much help I would be, but I'd be willing to give it a shot if someone could point me in the right direction :)

In any case thanks for the work you've done so far, it's already very useful as it is.

**Comment by jhayley** [comment]
Hello damian! Unfortunately it's been a little bit since i took a look at this (as you can probably see).

First, I'm not seeing the `npm install` issue that you're having on their branch. I'm confused about that error because nothing should be looking for bondage in node_modules anyway...are there more details you could provide?

Second, as a long overdue thing, I'm going to pull ephread's changes in the `parser-update` into this repo under the `wip-yarnspinner-parity` branch so I can take a look at it here.

It'll take me a bit to get up to speed and I have a full time job now, but I'll try to help you along as best I can!

**Comment by jhayley** [comment]
After going over all this and ephread's changes. It looks like I'll just need to rewrite the runner (it desperately needed it anyway) to improve what it outputs it should be usable at the very least. I might generalize it so there's more to handle on the user's end (returning more or less the info from the ast as an object that you have to use, and making you need to restart the parser for each node) to make this process simpler, but we'll see where it ends up. Let me know if you have any thoughts

**Comment by jhayley** [comment]
@damian0815 in the wip-yarnspinner-parity branch I've updated the runner to use shortcut options (and updated the README with instructions). still gotta look at implementing variables and stuff but it should be a bit more usable for you now!

**Comment by damian0815** [comment]
Hey, thanks! Sorry I haven't replied yet, i've been trying to find the time to give this a proper look.
