### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by justjuank** [jhayley/bondage.js#27]
Hi, I think the **npm install bondage** is not working.
Every time I run it I get this:

1270 warn New folder No description
1271 warn New folder No repository field.
1272 warn New folder No README data
1273 warn New folder No license field.
1274 verbose stack Error: ENOENT: no such file or directory, chmod 'C:\Users\JuanK\Documents\New folder\node_modules\bondage\bin\bondage.js'
1275 verbose cwd C:\Users\JuanK\Documents\New folder
1276 verbose Windows_NT 10.0.16299
1277 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\JuanK\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "bondage"
1278 verbose node v8.10.0
1279 verbose npm  v5.8.0
1280 error path C:\Users\JuanK\Documents\New folder\node_modules\bondage\bin\bondage.js
1281 error code ENOENT
1282 error errno -4058
1283 error syscall chmod
1284 error enoent ENOENT: no such file or directory, chmod 'C:\Users\JuanK\Documents\New folder\node_modules\bondage\bin\bondage.js'
1285 error enoent This is related to npm not being able to find a file.
1286 verbose exit [ -4058, true ]

Am I missing something?

**Comment by jhayley** [comment]
Ah! Thanks for pointing this out, should be fixed now

**Comment by justjuank** [comment]
Awesome, it's working now, thank you! Great job with this by the way :)
