### ISSUE TITLE
Question: Detect error on unexisting Node

### ISSUE THREAD

**Issue by justjuank** [jhayley/bondage.js#30]
Hi, is there a way to catch an error when running `const d = runner.run('Start')` ?
I would like to catch the error before running `let result = d.next().value;`
Thanks.

**Comment by justjuank** [comment]
Yes, it is throwing the error but I'm not able to catch it in order to act accordingly. For example I would like to load the "Start" node if a different node fails to load so it would be like a fallback in case my system can't load a specific node (Assuming all my dialogues would contain at least a Start node).

**Comment by justjuank** [comment]
Yeah I tried that, but I just realized that the error is thrown after you call .next()
I was trying like this:
```
try{
	this.node = this.runner.run(atNode);
}
catch(error){
	console.log(error);
}
```
So there's no way to know if a node exists before calling .next() ?

**Comment by jhayley** [comment]
Oh! I apologize for misunderstanding. I don't believe there is a way right now for you to do that via the function call but `this.runner.yarnNodes['nodename'] === undefined` will let you check in advance if it doesn't exist

**Comment by justjuank** [comment]
No need to apologize, and yes! that works perfectly, just what I needed, thank you very much!
