### ISSUE TITLE
Load/Save story state of bondage.js (all variables) in the host game engine using bondage

### ISSUE THREAD

**Issue by blurymind** [jhayley/bondage.js#43]
How does one read/write to bondage.js runner's variables - outside of bondage.js? 
I am getting closer to bundling bondage.js as an extension in gdevelop. One last feature that I am missing is the ability to do load/save game states to remember player's choices in previous sessions.

So when making choices in bondage.js, it sets/gets variables to decide which dialogue tree to take.  I was wondering if we can store all these variables to an object and set/get them on initiation/termination of bondage.js - so as to pass them externally the the game engine using bondage.js and write to a game save file.

Ideally be able to store and restore the entire state of the runner with all of its variables

If that feature is missing atm, any pointers on where it would be appropriate to add it?  :)

**Comment by jhayley** [comment]
You can set a custom variable storage with your own class using `runner.setVariableStorage(obj)` which you can pass in a class that contains a `get(name)` and `set(name, value)` and bondage will write to that instead!!
