### ISSUE TITLE
building for web errors

### ISSUE THREAD

**Issue by blurymind** [jhayley/bondage.js#47]
Seems like the web build is super outdated. I had a go building it with

`node node_modules/gulp/bin/gulp
`
Then got these errors
```
ERROR in ./target/runner.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./parser/parser.js in E:\DEV\bondage.js\target
 @ ./target/runner.js 7:13-42

ERROR in ./target/runner.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./parser/nodes.js in E:\DEV\bondage.js\target
 @ ./target/runner.js 10:16-44
```

Is this something I am doing wrong or a genuine bug?
It spits up a new minified file, but it's only a third of the size of what is in dist to start with. I guess the error interrupted it ?

**Comment by jhayley** [comment]
Hmm yeah I haven't run this in a whiiile. I'm able to repro this on my end. Lemme see if there's a quick fix

**Comment by jhayley** [comment]
Great news! I think this was an extremely easy fix. Can you verify that the new bondage.min.js in #48 works for you before I merge it in (I can't test it right now)

**Comment by blurymind** [comment]
Thank you 😸  I will give it a try now

**Comment by blurymind** [comment]
Seems to work alright :) not sure if you would need to update the web demo for the new command line parsing - if it uses the same minified script.

Btw @4ian had a few notes on the web build of bondagejs, but he had a look on the old version
https://github.com/4ian/GDevelop/issues/1077#issuecomment-499213063
